FROM python:3.8-slim

COPY requirements.txt .

RUN set -ex; \
  	pip install --no-cache-dir -r requirements.txt

ADD kafka-consumer.py .

CMD ["python", "-u", "./kafka-consumer.py"]

# docker build -t kafka-consumer .
# docker run --network=host -it --rm kafka-consumer 

#KAFKA_BROKERS=localhost:54595,localhost:54601,localhost:54600